version: '3'
services:

  app:
    image: ender25/laravel-php-7.2-fpm:latest
    container_name: laravel_app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ../:/var/www
    networks:
      - app-network

  server:
    image: nginx:alpine
    container_name: laravel_server
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../:/var/www
      - ./nginx/:/etc/nginx/conf.d/:ro
    networks:
      - app-network

  db:
    image: mariadb:10
    container_name: laravel_db
    restart: unless-stopped
    tty: true
#    ports:
#      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - app-network

  redis:
    image: redis
    container_name: laravel_redis
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
